version: '3.7'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/log/access.log:/var/log/nginx/access.log
  web:
    image: nginx:latest
    expose:
      - "8080"
    volumes:
      - ./front/build:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/api_error.log:/var/log/nginx/api_error.log
      - ./nginx/log/api_access.log:/var/log/nginx/api_access.log